name: Add label auto-update to new pull request

on:
    pull_request:
        types: [opened, reopened]
        branches:
            - development

jobs:
    add-label-auto-update:
      permissions: write-all
      uses: 'SaaS-Innova/github-action/.github/workflows/add-label-auto-update.yml@main'
      with:
        label: "auto-update"
      secrets:
        token_for_github_api: ${{ secrets.PERSONAL_TOKEN_FOR_WORKFLOW }}
