name: Deploy to Glesys Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]

jobs:
  deploy:
    uses: 'SaaS-Innova/github-action/.github/workflows/frontend-development.yml@main'
    with:
      hostname: "46.246.48.92"
      user: "saas-innova-root"
      target: "main"
      destination: "~/repos/HappyFlowReact"
      fingerprint: "46.246.48.92 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCvVhfy3+147G/HRXZYmg6pqkiEthrxDiVRZuMe6vOfdMrzwrx/aAwuQ+UbNrKM1anI0nUfb1g7cS63v5IUdVoz2gaMWclDR2AOY/m1rPuksYi8FmmCdJie+txf/IKfLGJRyQT7PSpc9iiD3Hlssl4LPZX/gLfLeKCQ1ua7sVN07GWbUfZQilb3zfwqkpy8QfDKmlSg9bKET6JozXle9yAEuCG+6aPUUoRh3AS3oyoNub83oSD7qVEjLOp1bpejBUyRiBWnPCB14npqdKzUezPlhtS/XulHmNv5mbL5yPDbBVn+m+tbAocNoNB+3wfKjA9ihHhZaLRcHWi43gePJgV45NVp6DUBCkep4TUUHG67X5+exJCaPphrPfFJi7F5hpnF4PbshsJdHagyKMw86Y9lzT63f9b1E85vqW51xPElbAqYU4/IFKUKOxsDmoJ+iR6TGbSo1JCWZweftud/wSeQn3+eu16Qi32Kg6NaWfDjsBWb2Ljn29PR64ftGQvD6ws="
      pm2_name: 'HappyFlowFE'
    secrets:
      password: ${{ secrets.PROD_PASSWORD }}
      dotenv_key: ${{ secrets.PROD_DOTENV_KEY }}
      token_for_github_api: ${{ secrets.PERSONAL_TOKEN_FOR_WORKFLOW }}