name: 'Pull Request Workflow'

on:
  pull_request:
    types: [opened, ready_for_review, reopened, edited, synchronize]

jobs:
  prettier:
    uses: 'SaaS-Innova/github-action/.github/workflows/prettier.yml@main'
    with:
      prettier_options: '--check **/*.tsx'
    secrets:
      token_for_github_api: ${{ secrets.PERSONAL_TOKEN_FOR_WORKFLOW }}

  add-review:
    permissions: write-all
    uses: 'SaaS-Innova/github-action/.github/workflows/auto_assign.yml@main'
    with:
      reviewers: "RohitGoyani"
    secrets:
      token_for_github_api: ${{ secrets.PERSONAL_TOKEN_FOR_WORKFLOW }}
  
  test-build:
    uses: 'SaaS-Innova/github-action/.github/workflows/test-build-app.yml@main'
    with:
      graphql_url: ${REACT_APP_GRAPHQL_URL} > .env
      public_url: ${REACT_APP_PUBLIC_URL} >> .env
    secrets:
      token_for_github_api: ${{ secrets.PERSONAL_TOKEN_FOR_WORKFLOW }}

  purge-css:
    uses: 'SaaS-Innova/github-action/.github/workflows/purgecss.yml@main'
    secrets:
      token_for_github_api: ${{ secrets.PERSONAL_TOKEN_FOR_WORKFLOW }}
